### ISSUE TITLE
Não use alert()

### ISSUE THREAD

**Issue by igorknop** [ufjf-dcc121/2019-1-dcc121-lst1-rafaelstjf#1]
https://github.com/ufjf-dcc121/2019-1-dcc121-lst1-rafaelstjf/blob/master/qst15.html
O uso de alert() é uma prática a ser evitada. Troque para manipulação do DOM.

**Comment by rafaelstjf** [comment]
Beleza, troquei por manipulação no DOM. Decidi colocar para adicionar ao innerHTML da melhoria um parágrafo para cada disciplina abaixo da média.
